name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows as the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your code

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use JDK 11 for building your project

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\.m2\repository  # Cache Maven dependencies on Windows
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on pom.xml file
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install  # Run Maven build command

      - name: Run Tests with Maven
        run: mvn test  # Run Selenium tests with Maven

      - name: Upload test results to GitHub
        if: always()  # This ensures it runs even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target\surefire-reports  # Adjust path to where your test results are generated
