name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.m2\repository  # Cache Maven dependencies on Windows
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on pom.xml file
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install  # Run Maven build command

      - name: Run Tests with Maven
        run: mvn test  # Run Selenium tests with Maven

      - name: Upload test results to GitHub
        if: always()  # This ensures it runs even if tests fail
        uses: actions/upload-artifact@v4.3.0
        with:
          name: test-results
          path: test-output/*.html # Adjust path to where your test results are generated
